// Generated by https://quicktype.io

export interface Reservas {
    idReserva:     string;
    codHoomvip:    string;
    idCliente:     string;
    estado:        Estado;
    recibida:      string;
    entrada:       string;
    salida:        string;
    idApartamento: string;
    precioReal:    number;
    precioChannel: number;
    precioTotal:   number;
    comPortal:     number;
    comTarjeta:    number;
    extraMascota:  number;
    extraPax:      number;
    anticipo:      number;
    ocupacion:     number;
    adultos:       number;
    ninos:         number;
    bebes:         number;
    noches:        number;
    idPortal:      string;
    urlFactura:    string;
    cliente:       Cliente;
}

export interface Cliente {
    idCliente: string;
    nombre:    string;
    email:     string;
    telefono:  string;
    direccion: string;
    poblacion: string;
    cp:        string;
    pais:      Pais;
    idioma:    string;
}

export enum Pais {
    Alemania = "Alemania",
    Bélgica = "Bélgica",
    Empty = "",
    España = "España",
    Francia = "Francia",
    Irlanda = "Irlanda",
    Italia = "Italia",
    PaísesBajos = "Países Bajos",
    Rusia = "Rusia",
}

export enum Estado {
    Anulada = "Anulada",
    Confirmada = "Confirmada",
}

export enum IDApartamento {
    InvMojacar = "InvMojacar",
    InvTerreros = "InvTerreros",
}

export enum IDPortal {
    Abnb = "abnb",
    Avbok = "avbok",
    Book = "book",
    Personal = "personal",
}
